#!/usr/bin/env python
import subprocess

#declaring variable and assigning values. 

MESSAGES = "tail /var/log/messages"
SPACE = "df -h"

## Variables into a list/arry

cmds = [MESSAGES, SPACE]

count=0
for cmd in cmds:
	count+=1
	print "Running Command Number %s" % count
	subprocess.call(cmd, shell=True)

